---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: people-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mysql-secret
            - name: MYSQL_DATABASE
              value: peopledb
          image: mysql:8.0
          livenessProbe:
            exec:
              command:
                - sh
                - '-c'
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 60
            periodSeconds: 20
          name: mysql
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command:
                - sh
                - '-c'
                - mysqladmin ping -h 127.0.0.1 -uroot -p"$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 20
            periodSeconds: 10
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: mysql-init
              subPath: init.sql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
        - configMap:
            name: mysql-init
          name: mysql-init
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: people-app
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP